networks:
  cassandra-net:
    driver: bridge

services:
  cassandra-1:
    image: 'cassandra:latest' # cassandra:4.1.3
    container_name: 'cassandra-1'
    ports:
      - 7001:7000
      - 9042:9042
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_START_RPC=true # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0 # default
      - CASSANDRA_LISTEN_ADDRESS=auto # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
    volumes:
      - cassandra-node-1:/var/lib/cassandra:rw
    restart: on-failure
    healthcheck:
      test: ['CMD-SHELL', 'nodetool status']
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

  cassandra-reaper:
    image: 'thelastpickle/cassandra-reaper:latest'
    container_name: 'cassandra-reaper'
    ports:
      - '8090:8080'
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_REAPER_CASS_HOST=cassandra-1 # Hostname or IP of any Cassandra node
      - CASSANDRA_REAPER_CASS_CLUSTER_NAME=my-cluster
      - CASSANDRA_REAPER_CASS_DC=my-datacenter-1
      - CASSANDRA_REAPER_CASS_INITIAL_DELAY=15 # Adjust based on cluster startup time
      - CASSANDRA_REAPER_ENABLE_DYNAMIC_SEED_PROVIDER=true
    depends_on:
      - cassandra-1
    restart: always

  cassandra-2:
    image: 'cassandra:latest' # cassandra:4.1.3
    container_name: 'cassandra-2'
    ports:
      - 9043:9042
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_START_RPC=true # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0 # default
      - CASSANDRA_LISTEN_ADDRESS=auto # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
      - CASSANDRA_SEEDS=cassandra-1
    depends_on:
      cassandra-1:
        condition: service_healthy
    volumes:
      - cassandra-node-2:/var/lib/cassandra:rw
    restart: on-failure
    healthcheck:
      test: ['CMD-SHELL', 'nodetool status']
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

volumes:
  cassandra-node-1:
  cassandra-node-2:
