apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileupload-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fileupload-service
  template:
    metadata:
      labels:
        app: fileupload-service
    spec:
      containers:
        - name: fileupload-service
          image: bvquoc/fileupload:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50054
            - containerPort: 9090
          env:
            - name: SERVICE_PORT
              value: "50054"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: fileupload-service
spec:
  selector:
    app: fileupload-service
  ports:
    - name: grpc
      protocol: TCP
      port: 50054
      targetPort: 50054
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fileupload-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fileupload-service
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
        - type: Percent
          value: 100 # Scale down by a percentage of the current replicas
          periodSeconds: 5 # Check and possibly scale down every 60 seconds
    scaleUp:
      stabilizationWindowSeconds: 0 #
      policies:
        - type: Percent
          value: 100
          periodSeconds: 2
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
